### ISSUE TITLE
Проблема с переходом на версию Django 1.8. Выдает ошибку. При попытке установить и запустить через virtualenv в среде Django 1.4(в котором проект был создан) пока тоже не дал результатов, т.к. требует установить дополнительные пакеты (наподобие PIL). Пытался править классы согласно новой документации по 1.8, пока безрезультатно. Как же, все-таки, можно перенести проект на современную платформу?

### ISSUE THREAD

**Issue by pyshum** [whitemaster/payforward#1]
root@aspirin:~/payforward# python manage.py runserver 0.0.0.0:8080
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/usr/lib/python2.7/dist-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/loginza/models.py", line 7, in <module>
    User = get_user_model()
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/**init**.py", line 137, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by whitemaster** [comment]
Прежде чем понять как, я всегда задаю вопрос: зачем?! Между 1.8 и 1.4 - пропасть, тот же south стал частью django и сильно изменился, есть ещё множество особенностей. Не думаю, что с этого следует начинать обучения django. Попробуйте для начала разобраться как оно работает, установить virtualenv, создать окружение, установить в него: django==1.4 pillow, loginza, soutch, MySQL-python В  DjangoLive я подробно описывал процесс установки в процессе работы.

а потом, имея на руках рабочую копию, уже можно думать о модификациях.
